busykoala/fastapi-opa

README.md

Close #2 
This adds the reference to the wiki quickstart setup. I believe it won´t be too quick to get started with it but it also involves
the complete setup that was almost production-ready (except for some security-related configurations).

Add wiki link and adapt roadmap.

---

CHANGELOG.md
README.md
fastapi_opa/auth/auth_oidc.py
pyproject.toml
tests/utils.py

The well-known endpoint was Keycloak specific and also didn´t allow to use of the OIDC authentication without the
use of a well-known endpoint. With the change of this PR the interface of the OIDC config object changes so that
one can choose between providing the _complete_ well-known endpoint or all the endpoints (allowing to operate with
brokers not having a well-known endpoint).
Close #12 
The PR adapts the OIDC config object allowing the different approach plus checks which approach was chosen within the init
method (raising an exception if the information provided will not be sufficient).

Make OIDC config more flexible

---

.github/workflows/build.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
tests/test_oidc_auth.py

Since it is not really a requirement of the dependencies to force users to use python > 3.9 this change adds support for older versions as well.
Close #13

Add support for older python versions.

---

CHANGELOG.md
poetry.lock
pyproject.toml

Uvicorn is not necessary for the library. Therefore it can be removed.
Close #17

Remove uvicorn as a necessary dependency.

---

CHANGELOG.md
fastapi_opa/auth/auth_oidc.py

The endpoint is not necessary if the HS256 algorithm is used and therefore should be optional for the oidc flow.
The provided fix will raise an exception in the context of not having an endpoint.
Close #16

Make jwks endpoint optional.

---

CHANGELOG.md
poetry.lock
pyproject.toml

This change makes it more flexible to install the library.
There was not really a reason to put specific versions of the packages in the first place.
The only pkg with a min version is fastapi which has some known flaws in the previous versions.
If there are requirements regarding the deps we can re-add the specific requirement in a later state with a reason for it.
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_

Remove fixed dependency versions.

---

CHANGELOG.md
poetry.lock
pyproject.toml

This change will allow updating fastapi to versions >= 0.66.
Also it forces updating fastapi to >= 0.65.2 due to a CVE in versions below:
https://snyk.io/vuln/SNYK-PYTHON-FASTAPI-1303092.
Close #34

Support fastapi >= 0.66 and force update.

---

CHANGELOG.md
fastapi_opa/opa/opa_middleware.py
tests/test_opa.py

Close #35 
Fastapi brings openapi docs by default.
The endpoints (/docs, /redoc and openapi.json) should not be protected by this middleware.
If they need to be hidden this can be done by changing the apps settings instead:
https://fastapi.tiangolo.com/advanced/conditional-openapi/?h=openapi#conditional-openapi-from-settings-and-env-vars
:exclamation: The fix does not yet modify the docs so that the endpoints appear protected.
The change excludes the endpoint `/docs`, `/redoc` and `/openapi.json` from being protected by the middleware.

Allow openapi endpoints

---

fastapi_opa/auth/auth_oidc.py
fastapi_opa/opa/opa_middleware.py

1. CORS "OPTIONS" requests should be not handled. 
2. When redirecting authorization request to identity provider, we should use 303 and not default 307, so that the method is switched to GET.
_How does this change address the problem?_
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_

Skip options request and switch redirect code

---

CHANGELOG.md
README.md
fastapi_opa/auth/auth_oidc.py
fastapi_opa/example_oidc.py
fastapi_opa/example_saml.py
fastapi_opa/opa/opa_config.py
fastapi_opa/opa/opa_middleware.py
pyproject.toml
tests/conftest.py

In my software, I have a mix of graphql and rest endpoints, so I need to use an injectable only on the graphql endpoints. We also wish to use some bearer token. Finally, the graphql injectable is not working in the current state (see https://github.com/tiangolo/fastapi/issues/394) for more details on the issue. I am proposing a simple hack.
We can now specify some endpoints to skip for an injectable and can use bearer token.
- [x ] There is a Changelog (`/CHANGELOG.md`)
- [x ] Version was adapted if necessary (`/pyproject.toml`)
- [x ] I tested the feature if necessary (unittests, manual testing)
- [x ] If libraries aren't used for all package usages they are extras
- [x ] I documented the changes

Implement skip_endpoints + format

---

CHANGELOG.md
README.md
fastapi_opa/auth/auth_oidc.py
fastapi_opa/opa/enrichment/graphql_enrichment.py
fastapi_opa/opa/opa_config.py
fastapi_opa/opa/opa_middleware.py
pyproject.toml
tests/test_oidc_auth.py
tests/test_opa.py
tests/utils.py

- Properly implement the access tokens
- Skip endpoints now uses regex
- Add the option to disable the id tokens or the access tokens
- For the id token, we are already using the access token. So in my implementation of the access token, I am simply skipping all the non necessary steps.
- I created a new function that check each regex in `skip_endpoints`.
- I have added a new parameter to `OpaConfig` in order to use either id tokens or the access tokens (or both).

Implement properly access tokens, improve skip endpoints with regex

---

CHANGELOG.md
README.md

Contributors were listed using contrib.rocks. Since the contribution graph does not seem to show fork-PR contributions this MR adds a list of manual avatars.
Also the avatars include a URL to the user profiles now.
contrib.rocks is replaced with a manual list of avatars using the github API endpoint.

Add missing contrib avatars.

---

CHANGELOG.md
fastapi_opa/opa/opa_middleware.py
pyproject.toml

When using startup events in some endpoints (`@fastapi.APIRouter().on_event("startup")`), fastapi-opa is crashing the initialization.
The middleware is now skipping all the requests with type "lifespan" (see https://asgi.readthedocs.io/en/latest/specs/lifespan.html)
I have manually tested within phisherman and everything is working with this change.

Skip lifespan events (server startup / shutdown)

---

CHANGELOG.md
fastapi_opa/opa/opa_middleware.py
pyproject.toml

Starlette does not allow to access the body of a request multiple times. The current solution requires mock but it does not work when processing multiple requests at the same time (memory corruption and then all the requests will receive the same response).
Here, I am manually mocking the receive variable and send it back to the middleware stack. The difference with the previous solution is that I am doing a local mock and not a global one.

Fix multiple access to request body

---

CHANGELOG.md
poetry.lock
pyproject.toml

Due to the vuln [CVE-2022-29217](https://github.com/advisories/GHSA-ffqj-6fqr-9h24) this update is required.

[Sec]: Bump pyjwt to >= 2.4.

---

CHANGELOG.md
README.md
fastapi_opa/auth/auth_api_key.py
fastapi_opa/opa/opa_config.py
fastapi_opa/opa/opa_middleware.py
pyproject.toml
tests/conftest.py
tests/test_api_key_auth.py
tests/test_opa.py
tests/utils.py

For some services, we need an efficient way to access some endpoints protected by fastapi-opa without going through the authentication server.
Here, I am implementing a authentication method for API key and allows multiple authentication methods in the middleware.

Implement API Key + allow multiple authentication methods

---

.github/workflows/build.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_enrichment_graphql.py
tests/test_opa.py

To fix remote code execution using GitPython (https://github.com/advisories/GHSA-hcpj-qp55-gfph) this version should be bumped to a not affected version (this update lead to dropping python 3.6).
Additionally, package updates were done and two tests fixes which were using the http get method with a json parameter (changed to post now).
Bump GitPython to a version higher than 3.1.29

Bump GitPython to fix RCE.

---

.flake8
CHANGELOG.md
poetry.lock
pyproject.toml

This was necessary since https://github.com/busykoala/fastapi-opa/commit/ced66abfecea1b5c7c541cd2b9edfffc9e33b044 because flake9 did not adapt to the importlib-metadata upgrades.
Since this issue is still not fixed in flake9 it's time to move on and use flake8 after all.
close #63
The pinning can be removed moving on with flake8.
The removal of the pinning makes the package more flexible in use.

Remove transitive pinning.

---

CHANGELOG.md
fastapi_opa/opa/opa_config.py
pyproject.toml
tests/test_opa.py

I am using OPA policies with different package names than the currently assumed `package httpapi.authz`. When doing so, I need the middleware to make a request to a different path instead of `v1/data/httpapi/authz` to use my policy/package. In order to achieve this, a new parameter is added to the `OPAConfig` to change the `opa_url` according to the package name.
The new parameter is used to update the `opa_url` which then points to the expected policy.
See official OPA Data REST Endpoint [docs](https://www.openpolicyagent.org/docs/latest/rest-api/#data-api).

Add option to specify policy package names.

---

.github/workflows/build.yaml
CHANGELOG.md
fastapi_opa/auth/auth_api_key.py
fastapi_opa/auth/auth_oidc.py
fastapi_opa/auth/auth_saml.py
fastapi_opa/opa/opa_middleware.py
poetry.lock
pyproject.toml

To mitigate [CVE-2024-24762](https://github.com/advisories/GHSA-qf9m-vfgh-m389), 
we need to update FastAPI. This update necessitates discontinuing support for 
Python 3.7.
To ensure our FastAPI dependency is secure, we've pinned it to a version that 
addresses the vulnerability. However, this version also discontinues support 
for Python 3.7, requiring us to do the same.

Update fastapi due to vulnerability.

---

.github/workflows/build.yaml
.gitignore
CHANGELOG.md
assets/shell.nix
fastapi_opa/opa/opa_middleware.py
poetry.lock
pyproject.toml

Make linting and formatting easier with a smaller toolset this change replaces flake8, isort and black with ruff.
The change replaces the tooling with the least changes in the code. Also the pipeline changes a little accordingly.

Move to ruff for formatting & linting.

---

CHANGELOG.md
tests/test_oidc_auth.py

There were some deprecation warnings in the test runs. This change fixes those warnings and improves the test output.
Remove context manager in patching and directly access the JsonWebKey.

Fix deprecation warning in tests.
